[project]
name = "mazegen"
version = "1.0.0"
description = "maze generation and visualization with a navigation menu"
authors = [
    {name = "Tobias Sordo Ostolaza",email = "tsordo-o@student.42malaga.com"},
    {name = "Jean Roland Steven Vera Cruz",email = "jvera-cr@student.42malaga.com"}
]
license = {file = "../LICENSE.md"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic (==2.13.4)",
    "pydantic-core (==2.46.4)",
    "typing-inspection (==0.4.4)",
    "typing-extensions (==4.16.0)"
]


[tool.poetry]
packages = [{include = "mazegen", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
clean = "rm -rf build dist *.egg-info _path_finder/*.egg-info gen_algorithms/*.egg-info"
build = "task clean && python3 -m build --wheel && mv dist/*.whl . && task clean"

[dependency-groups]
dev = [
    "fawltydeps (>=0.20.0,<0.21.0)"
]
