[project]
name = "mazegen"
version = "1.0.0"
description = "maze generation and visualization with a navigation menu"
authors = [
    {name = "Tobias Sordo Ostolaza",email = "tsordo-o@student.42malaga.com"},
    {name = "Jean Roland Steven Vera Cruz",email = "jvera-cr@student.42malaga.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]


[tool.poetry]
packages = [{include = "mazegen", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
